### ISSUE TITLE
AccessDeniedException when running local integration tests

### ISSUE THREAD

**Issue by fitztrev** [tors42/chariot#12]
Getting this error after https://github.com/tors42/chariot/commit/4c18452ca72ff91c0cdfd6909c484778259a0d7f

```bash
$ ./build/integration/local 

Running integration tests
5e2b68b4332027e1a9a090e58087e20729f82ce4a77236b0573e52710cf31aab
99113b5c60972a29262e6221247f56968e5a5f6fb15a496604f0a412422a5320
Exception in thread "main" java.nio.file.AccessDeniedException: /app/out
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:438)
        at java.base/java.nio.file.Files.createDirectory(Files.java:699)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
        at java.base/java.nio.file.Files.createDirectories(Files.java:793)
        at build.Build.build(Build.java:39)
        at build.Build.main(Build.java:18)
⌛ Waiting for lila to start...
⌛ Waiting for lila to start...
⌛ Waiting for lila to start...
⌛ Waiting for lila to start...
⌛ Waiting for lila to start...
Error occurred during initialization of boot layer
java.lang.module.FindException: Module testchariot not found
```

**Comment by tors42** [comment]
Oh.

During a build (`java build/Build.java`), a directory `./out/` is deleted and re-created.

I noticed that when not telling docker to run as my normal user, it would create the `out` directory as user `root`.
So after running `./build/integration/local`, I would have a `./out/` directory owned by `root` in my filesystem.

If I later run `java build/Build.java` (as my normal user), it would fail because I am not allowed to touch the directory owned by `root`.

Have you tried a new checkout (or `sudo rm -rf ./out/`)? Maybe an old `root`-owned directory is interfering.

Or maybe it helps with adding `:Z` to the volume mount (a SELinux thing it seems, after quick search for "docker" and "file permission" -> `... -v $(pwd):/app:Z ...`)

If this doesn't solve the problem, I'm inclined to have the `run-tests.sh` script delete the `out` directory when it is finished...

**Comment by tors42** [comment]
Yeah, I've reverted https://github.com/tors42/chariot/commit/4c18452ca72ff91c0cdfd6909c484778259a0d7f and now remove the `./out/` directory from `run-tests.sh`,
this makes things simpler! Thanks!

**Comment by fitztrev** [comment]
Working now, thanks!
