### ISSUE TITLE
No enum constant chariot.model.StatsPerfType.standard

### ISSUE THREAD

**Issue by mcoria** [tors42/chariot#16]
Hi,

I've been using this library for a couple of months, but recently I haven't been able to retrieve my bot rating.

Even after updating to the most recent library version: 0.0.84

Whenever I execute:

`        Map<StatsPerfType, StatsPerf> rating = client.account()
                .profile()
                .get()
                .ratings();`

I get the following exception

`java.lang.IllegalArgumentException: No enum constant chariot.model.StatsPerfType.standard
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at chariot@0.0.84/chariot.model.StatsPerfType.valueOf(StatsPerfType.java:3)
	at chariot@0.0.84/chariot.internal.ModelMapper.lambda$static$22(ModelMapper.java:393)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:179)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at chariot@0.0.84/chariot.internal.ModelMapper.lambda$static$26(ModelMapper.java:392)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at chariot@0.0.84/chariot.internal.ModelMapper.lambda$static$29(ModelMapper.java:447)
	at chariot@0.0.84/chariot.internal.ModelMapper.lambda$static$30(ModelMapper.java:469)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at chariot@0.0.84/chariot.internal.Endpoint$Builder.lambda$elementMapper$0(Endpoint.java:655)
	at chariot@0.0.84/chariot.internal.Endpoint$EPOne.lambda$newRequest$0(Endpoint.java:28)
	at chariot@0.0.84/chariot.internal.RequestParameters$ReqOne.process(RequestParameters.java:35)
	at chariot@0.0.84/chariot.internal.impl.AccountHandler.profile(AccountHandler.java:22)`

I would appreciate your help.

Thanks,
Mauricio

**Comment by tors42** [comment]
Thanks for reporting,
I could reproduce the problem with your example! :bow: 

This has been fixed in chariot-0.0.86 :tada:

**Comment by mcoria** [comment]
@tors42 

It works now for me. Great work you're doing with this library !!!!!

Thank you,
Mauricio
